### ISSUE TITLE
"Thematic content reccomendations"

### ISSUE THREAD

**Issue by adenta** [ankane/disco#28]
So I understand how Disco can tell me, "Similar users with similar preferences liked _this_ content"

What I'm unclear on is if Disco can tell me, "You liked this video of a guy playing guitar. Here is another video of a _different_ guy playing the guitar".

  - is there an industry standard way to direct users towards similar content, without a large volume of user generated data? Is this a manual tagging process, or is there something automated that can be utilized? I kinda feel like [this](https://xkcd.com/1425/) XKCD, and am fully prepared to learn that this will be exceptionally difficult.
  - Would I need to store this additional recommendation in a different way? Could I pipe this thematic linking of data into Disco?

BTW great name, I too am [Andrew](https://denta.co)

**Comment by ankane** [comment]
Hey @adenta, Disco already does this to some degree. You can think of each factor as a theme, and instead of generating them yourself, matrix factorization generates them (so they won't have human-readable labels).

Unfortunately, I don't have the bandwidth to help more with this, but I'd recommend checking out resources on matrix factorization to learn more about how it works.
